language: ruby
rvm:
- 2.5.3
services:
  - mysql
branches:
  only:
  - master
  - /quarter\d*/
  - develop
  - /2.\d*.\d*/
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_reporting:prepare_rspec
- bundle exec rspec
before_install:
- mysql -e "create database IF NOT EXISTS transam_reporting_testing;" -uroot
bundler_args: --without not_travis